function getSuggestion() {
    const select = document.getElementById("issueSelect").value.toLowerCase();
    const text = document.getElementById("suggestionText");
    const box = document.getElementById("suggestionBox");
    const formCard = document.getElementById("formCard");
  
    if (!select) return;
  
    formCard.style.display = "none";
    box.style.display = "block";
    void box.offsetWidth; // trigger reflow
    box.classList.add("show");
  
    const remedies = {
      "headache": "Headaches can be caused by various factors like stress, dehydration, or lack of sleep. A cold compress on your forehead can help relieve the pain by constricting blood vessels. Ensure you're drinking enough water throughout the day, as dehydration is a common headache trigger. Try to rest in a quiet, dark room, as light and noise can worsen the pain. If the headache persists, consider taking an over-the-counter pain reliever, such as ibuprofen or acetaminophen, but always follow the recommended dosage.",
      "stomach pain": "Stomach pain can result from a variety of causes, including indigestion, gas, or a stomach virus. Drinking warm ginger tea can help soothe the stomach, as ginger has natural anti-inflammatory properties that aid digestion. It's also helpful to avoid eating heavy, greasy foods that could irritate your stomach further. If the pain is severe or persistent, it’s important to consult with a healthcare provider to rule out any underlying conditions like ulcers or gastrointestinal disorders.",
      "fever": "Fever is usually a sign that the body is fighting an infection. To help manage it, make sure to stay hydrated by drinking fluids like water, lemon water, or herbal teas. Rest is essential for recovery, so try to get plenty of sleep. You can use a damp cloth or take a lukewarm bath to help cool down the body. If the fever is high (over 102°F/39°C) or lasts for more than a couple of days, it’s important to consult a doctor to determine the cause and ensure proper treatment.",
      "joint pain": "Joint pain can be due to overuse, injury, or conditions like arthritis. Applying a warm compress to the affected area helps to increase blood flow and relax the muscles. Gentle movements or stretches can also prevent stiffness, but avoid any strenuous activity that could worsen the pain. You can also consider taking an anti-inflammatory medication (like ibuprofen) to reduce pain and swelling. If the pain is chronic or severe, it’s advisable to see a healthcare professional for further evaluation and management.",
      "skin rash": "Skin rashes can be caused by allergies, irritation, or infections. Applying aloe vera gel or coconut oil can help soothe irritation and provide moisture. Make sure to avoid scratching, as it can worsen the rash and increase the risk of infection. Wearing soft, loose-fitting clothing can also prevent further irritation. If the rash doesn’t improve within a few days or if it starts to spread, it’s important to consult with a healthcare provider to determine the cause and receive appropriate treatment.",
      "diabetes": "Managing diabetes requires careful attention to diet, exercise, and blood sugar levels. Eating a balanced diet rich in fiber and low in simple sugars can help regulate blood sugar. Cinnamon tea has been shown to have properties that may assist in controlling blood sugar levels. Regular exercise, such as walking or cycling, can also help maintain healthy blood sugar levels. It's important to monitor your blood sugar regularly and take any prescribed medications as directed by your healthcare provider.",
      "hypertension": "High blood pressure is a serious condition that can lead to heart disease if left unchecked. Reducing salt intake is one of the most effective ways to manage hypertension. In addition, practicing deep breathing or meditation can help reduce stress, which can contribute to high blood pressure. Regular physical activity, such as walking or swimming, can also help lower blood pressure over time. It’s crucial to have regular check-ups with your healthcare provider and take prescribed medication as needed to keep your blood pressure within a healthy range.",
      "chest pain": "Chest pain can have many causes, ranging from muscle strain to more serious conditions like heart problems. If the pain is sharp, sudden, or accompanied by symptoms like shortness of breath, dizziness, or nausea, seek medical attention immediately as this could be a sign of a heart attack. If the pain is more of a dull ache, it could be due to muscle tension or stress, and rest may help. Regardless, it’s essential to consult with a healthcare provider for an accurate diagnosis and appropriate care.",
      "fatigue": "Fatigue can result from insufficient sleep, stress, poor nutrition, or an underlying health condition. Make sure you’re getting enough sleep—adults typically need 7-9 hours per night. Staying hydrated is also crucial, as dehydration can contribute to feelings of fatigue. Taking short breaks throughout the day and engaging in light physical activity, like walking, can help boost your energy levels. If fatigue persists despite adequate rest, it may be a sign of an underlying issue, and it’s important to consult a healthcare professional.",
      "anxiety": "Anxiety can manifest in various ways, such as racing thoughts, rapid heartbeat, or excessive worry. Deep breathing exercises, such as the 4-7-8 technique (inhale for 4 seconds, hold for 7, exhale for 8), can help calm the nervous system. Drinking chamomile tea, known for its calming properties, can also provide relief. Engaging in physical activities, like yoga or walking, can help reduce anxiety over time by releasing endorphins. If anxiety becomes chronic or interferes with daily life, consider speaking with a healthcare provider for support and potential therapy options.",
      "insomnia": "Insomnia can be caused by stress, poor sleep habits, or underlying health issues. Drinking warm milk or chamomile tea before bed can help relax the body and mind. It’s also helpful to establish a consistent sleep schedule by going to bed and waking up at the same time every day. Avoid using electronic devices before bedtime, as the blue light can interfere with sleep. If insomnia persists for several weeks or disrupts daily functioning, it’s important to consult a doctor to address any underlying causes and explore treatment options.",
      "eye strain": "Eye strain can be caused by prolonged screen time or lack of sleep. The 20-20-20 rule is a helpful technique to alleviate strain: every 20 minutes, take a 20-second break and look at something 20 feet away. Blinking frequently helps to refresh your eyes and prevent dryness. Additionally, using artificial tears or eye drops can help relieve discomfort. If eye strain continues or if you experience vision changes, it’s important to consult an eye specialist for further advice.",
      "back pain": "Back pain can be due to poor posture, muscle strain, or underlying conditions like sciatica. Gentle stretching exercises, such as the cat-cow stretch or child’s pose, can help alleviate tension in the back muscles. Using a heating pad or warm compress can also help relax stiff muscles. If the pain is persistent or severe, or if it radiates down your legs, it's important to consult a healthcare provider to rule out any more serious issues.",
      "depression": "Depression can affect every aspect of life, making everyday activities feel overwhelming. Talking to someone you trust about how you’re feeling can be a helpful first step. Regular physical activity, such as walking or light exercise, can improve mood by releasing endorphins. Eating a healthy diet, rich in omega-3 fatty acids, vitamins, and minerals, can also support mental well-being. If depression persists, it's important to seek help from a healthcare provider who can recommend therapy or medication if necessary.",
      "cold/flu": "Cold and flu symptoms can be managed with rest, hydration, and over-the-counter medications. Drinking honey-lemon tea can help soothe a sore throat and reduce congestion. Resting and staying warm is important, as the body needs time to fight off the infection. Inhaling steam from a hot shower or bowl of water can help clear up nasal congestion. If symptoms persist or worsen, it’s important to consult a healthcare provider for further guidance.",
      "asthma": "Asthma can cause difficulty breathing, especially during physical exertion or exposure to triggers like pollen or smoke. Using a prescribed inhaler as directed is the most effective way to manage asthma symptoms. Steam inhalation can help open the airways, and avoiding known triggers is crucial. It’s also helpful to monitor your asthma symptoms and work with a healthcare provider to adjust your treatment plan as needed.",
      "sinus infection": "Sinus infections are often caused by viruses or bacteria and can result in symptoms like congestion, facial pressure, and headache. Using a warm compress on your face can help alleviate sinus pressure. Drinking plenty of fluids and inhaling steam can help clear the sinuses. Saline nasal sprays can also help moisturize nasal passages and reduce congestion. If the infection lasts more than a week or if symptoms worsen, it's important to consult a healthcare provider for further evaluation.",
      "acid reflux": "Acid reflux occurs when stomach acid flows back into the esophagus, causing discomfort or a burning sensation. Avoiding spicy or fatty foods, eating smaller meals, and avoiding lying down immediately after eating can help reduce symptoms. Drinking ginger tea can help soothe the stomach lining, and elevating the head of the bed can prevent acid from rising while you sleep. If acid reflux becomes frequent, it's important to consult with a healthcare provider for advice and possible medication.",
      "arthritis": "Arthritis is an inflammatory condition that affects the joints, causing pain, stiffness, and swelling. Low-impact exercises like swimming or walking can help keep the joints flexible. Applying a warm compress or taking a warm bath can also ease joint pain. Consuming anti-inflammatory foods, such as turmeric, omega-3-rich foods (like salmon), and leafy greens, can help reduce inflammation. If the pain is severe or persistent, it's important to seek medical advice for further management.",
      "allergies": "Allergic reactions can be triggered by various factors, including pollen, dust, or pet dander. Avoiding known allergens is the first step in managing allergies. Rinsing your nose with saline can help clear out any irritants, and using antihistamines can reduce symptoms. Keeping windows closed during peak pollen seasons and using air purifiers can also help reduce exposure. If allergies worsen or lead to complications, consult a healthcare provider for additional treatments."
    };
    
    
  
    text.textContent = remedies[select] || "Sorry, no remedy found.";
  }
  
  document.addEventListener('keydown', function () {
    const box = document.getElementById("suggestionBox");
    const formCard = document.getElementById("formCard");
  
    box.classList.remove("show");
    setTimeout(() => {
      box.style.display = "none";
      formCard.style.display = "block";
    }, 600);
  });
  
